version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datasynth
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.example
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/datasynth?schema=public
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend/storage:/app/storage
  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    ports:
      - "3000:3000"
    command: npm run dev
volumes:
  db_data: