apiVersion: apps/v1
kind: Deployment
metadata:
  name: datasynth-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: datasynth-backend
  template:
    metadata:
      labels:
        app: datasynth-backend
    spec:
      containers:
        - name: backend
          image: your-registry/datasynth-backend:latest
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              value: production
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: datasynth-secrets
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: datasynth-secrets
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: datasynth-backend
spec:
  selector:
    app: datasynth-backend
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP